# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 65ce68274f93dbdfd9c3c203c2457932f095204df2b816077ab548d0008810fd9dd3b8c38c85b0600249f73d75f5825630de1f3b8863d0fda7e4917060b0701a

test:
  secret_key_base: d45e702f4381ffd296132d4f0e67660d3d77ea2c62e19c7f125e08a1a530bb1771e472c72f64a94c34737cf5e555dbd104f77e6b740de2298c8f1df2aca35d4f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
